#!/usr/bin/env python3
"""
Claude bridge — bi-directional sync between a project's MEMORY.md
(or CLAUDE.md memory section) and the moma memory store.

Pull: reads MEMORY.md bullets → creates moma memories
Push: writes top moma memories → updates MEMORY.md

Usage:
  python3 scripts/claude_bridge.py pull /path/to/project
  python3 scripts/claude_bridge.py push /path/to/project [--project slug]
"""
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_DIR))

from moma import Storage, Memory, ids
from moma.storage import slugify
from moma.config import load as load_config


def _now():
    return datetime.now(timezone.utc).isoformat()


# ── Pull: MEMORY.md → moma ────────────────────────────────────────────────────

def pull(project_dir: str) -> dict:
    """Read bullet points from MEMORY.md / CLAUDE.md memory sections → moma."""
    storage = Storage()
    project_path = Path(project_dir)
    project_name = project_path.name
    project_slug = slugify(project_name)

    # Look for MEMORY.md or memory section in CLAUDE.md
    candidates = [
        project_path / "MEMORY.md",
        project_path / ".claude" / "MEMORY.md",
        project_path / "CLAUDE.md",
    ]
    text = ""
    source_file = None
    for candidate in candidates:
        if candidate.exists():
            text = candidate.read_text()
            source_file = str(candidate)
            break

    if not text:
        return {"error": "no MEMORY.md or CLAUDE.md found", "project_dir": project_dir}

    # Extract bullet points (lines starting with - or *)
    bullets = re.findall(r"^[-*]\s+(.+)$", text, re.MULTILINE)
    if not bullets:
        return {"pulled": 0, "message": "no bullet points found in memory file"}

    now = _now()
    saved = 0
    for bullet in bullets:
        bullet = bullet.strip()
        if len(bullet) < 10:
            continue
        content_hash = hashlib.sha256(bullet.encode()).hexdigest()
        if storage.is_duplicate(content_hash):
            continue

        # Guess type from content
        mem_type = "fact"
        if any(w in bullet.lower() for w in ["prefer", "always", "never", "use "]):
            mem_type = "preference"
        elif any(w in bullet.lower() for w in ["bug", "crash", "error", "fix"]):
            mem_type = "bug"
        elif any(w in bullet.lower() for w in ["arch", "pattern", "structure", "design"]):
            mem_type = "architecture"

        # Title = first 80 chars, content = full bullet
        title = bullet[:77] + "..." if len(bullet) > 80 else bullet

        memory = Memory(
            id=ids.memory_id(),
            type=mem_type,
            scope="project",
            project=project_slug,
            title=title,
            content=bullet,
            concepts=[],
            files=[source_file or ""],
            importance=6,
            confidence=0.7,
            created_at=now,
            updated_at=now,
            session_ids=["claude-bridge"],
        )
        storage.save_memory(memory)
        storage.record_audit("memory_pulled", memory.id, f"from {source_file}")
        saved += 1

    return {"pulled": saved, "source": source_file, "project": project_name}


# ── Push: moma → MEMORY.md ────────────────────────────────────────────────────

def push(project_dir: str, project_slug: str = "") -> dict:
    """Write top moma memories into MEMORY.md in the project."""
    storage = Storage()
    project_path = Path(project_dir)
    if not project_slug:
        project_slug = slugify(project_path.name)

    mems = storage.list_memories(project_slug=project_slug)
    active = [m for m in mems if not m.get("superseded_by")]
    active.sort(key=lambda m: m.get("importance", 5), reverse=True)
    top = active[:20]

    lines = [
        f"# MEMORY.md — {project_path.name}",
        f"_Auto-generated by moma on {_now()[:10]}. Edit with care — changes are overwritten on next push._",
        "",
    ]

    by_type: dict[str, list] = {}
    for m in top:
        t = m.get("type", "fact")
        by_type.setdefault(t, []).append(m)

    for t, type_mems in sorted(by_type.items()):
        lines.append(f"\n## {t.capitalize()}")
        for m in type_mems:
            lines.append(f"- **{m['title']}**: {m['content']}")

    content = "\n".join(lines) + "\n"
    dest = project_path / "MEMORY.md"
    tmp = dest.with_suffix(".tmp")
    tmp.write_text(content)
    tmp.replace(dest)

    return {"pushed": len(top), "dest": str(dest), "project": project_path.name}


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python3 scripts/claude_bridge.py pull|push /path/to/project")
        sys.exit(1)
    action = sys.argv[1]
    project = sys.argv[2]
    if action == "pull":
        print(json.dumps(pull(project), indent=2))
    elif action == "push":
        slug = sys.argv[3] if len(sys.argv) > 3 else ""
        print(json.dumps(push(project, slug), indent=2))
    else:
        print(f"Unknown action: {action}")
        sys.exit(1)
